export async function collectKoreaData({ apiSources = [] } = {}) {
  const enabled = new Set(apiSources.filter(s => s.enabled).map(s => s.key));
  const sourceMode = enabled.size ? "api_ready_sample_snapshot" : "sample_snapshot";
  const now = new Date().toISOString();

  return [
    {
      vessel_id: "IMO-9876543",
      vessel_name: "MV HF ZHOUSHAN",
      port: "Busan",
      berth: "Outer Anchorage",
      anchorage_zone: "Busan OPL",
      status: "Waiting",
      operator: "Sample Operator",
      destination: "Australia",
      previous_port: "Port Hedland",
      next_port: "Brisbane",
      vessel_type: "Capesize",
      gt: 93000,
      eta: "2026-05-04 08:00",
      etb: "2026-05-27 10:00",
      ata: "2026-05-04 07:40",
      atb: "",
      etd: "2026-05-29 18:00",
      atd: "",
      days_in_korea: 21,
      speed: 2,
      risk_score: 95,
      source: "integrated_vts_sample",
      updated_at: now,
      source_mode: sourceMode,
      api_ready: [...enabled]
    },
    {
      vessel_id: "IMO-8111222",
      vessel_name: "MAERSK DEMO",
      port: "Ulsan",
      berth: "Industrial Berth",
      anchorage_zone: "",
      status: "At Berth",
      operator: "Maersk",
      destination: "Singapore",
      previous_port: "Shanghai",
      next_port: "Singapore",
      vessel_type: "Container",
      gt: 76000,
      eta: "2026-05-20 09:00",
      etb: "2026-05-20 16:00",
      ata: "2026-05-20 08:45",
      atb: "2026-05-20 16:20",
      etd: "2026-05-25 21:00",
      atd: "",
      days_in_korea: 5,
      speed: 10,
      risk_score: 35,
      source: "ulsan_port_schedule_sample",
      updated_at: now,
      source_mode: sourceMode,
      api_ready: [...enabled]
    },
    {
      vessel_id: "IMO-7000001",
      vessel_name: "YEOSU TARGET",
      port: "Yeosu",
      berth: "Outer Anchorage",
      anchorage_zone: "D",
      status: "Waiting",
      operator: "Demo Operator",
      destination: "Brazil",
      previous_port: "Singapore",
      next_port: "Brazil",
      vessel_type: "VLCC",
      gt: 160000,
      eta: "2026-05-09 03:00",
      etb: "",
      ata: "2026-05-09 02:35",
      atb: "",
      etd: "2026-05-31 12:00",
      atd: "",
      days_in_korea: 16,
      speed: 1,
      risk_score: 90,
      source: "integrated_vts_sample",
      updated_at: now,
      source_mode: sourceMode,
      api_ready: [...enabled]
    }
  ];
}
